###
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "qq_number": "2652446227",
  "qq_group": "123456789"
}

###
POST http://localhost:8080/demo/payload
Content-Type: application/json

{
  "id": "95255139906085392619"
}

###
POST http://localhost:8080/demo/domain
Content-Type: application/json

{
  "qq_number": "931731014"
}