spring:
  application:
    name: lpy-bot-server
  datasource:
    username: root
    password: aabbccdd
    url: jdbc:mysql://124.221.74.242:10011/robot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    property-naming-strategy: SNAKE_CASE
    locale: zh_CN
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler